name: Build/release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            make_cmd: make linux
            asset_name: juejin_collections-linux64
          - os: windows-latest
            make_cmd: make win
            build_shell: msys2 {0}
            asset_name: juejin_collections-win64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Setting node version
        uses: actions/setup-node@v4
        with:
          node-version: 16.12.0
          ## https://github.com/actions/setup-node#caching-global-packages-data
          cache: 'yarn'
          cache-dependency-path: './frontend/yarn.lock'

      - name: Setting go version
        uses: actions/setup-go@4
        with:
          # go-version: '1.17'
          go-version-file: 'go.mod'
          cache: true
          ## 将check latest设置为true会影响性能，因为下载Go版本比使用缓存版本慢。
          # check-latest: true

      ## https://github.com/getlantern/systray
      - name: Install Sys Module
        uses: awalsh128/cache-apt-pkgs-action@latest
        # Only Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        with:
          packages: libgtk-3-dev libayatana-appindicator3-dev
          version: 1.0
        # run: |
        #   sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev --fix-missing
        # shell: bash
      
      - name: Setup msys2 install sys module
        uses: msys2/setup-msys2@v2
        if: startsWith(matrix.os, 'windows')
        with:
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-sqlite3
          msystem: MINGW64
          path-type: inherit
      
      - name: Install Module
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          go mod download
          go install github.com/rakyll/statik
          cd ./frontend
          yarn install --frozen-lockfile --immutable
      
      - name: Start build
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          make -v
          pwd
          ${{ matrix.make_cmd }}
      
      # shell no abled setting 
      # https://github.com/actions/runner/issues/444
      - name: Install Module
        if: startsWith(matrix.os, 'windows')
        run: |
          go mod download
          go install github.com/rakyll/statik
          cd ./frontend
          yarn install --frozen-lockfile --immutable
        shell: msys2 {0}
      
      - name: Start build
        if: startsWith(matrix.os, 'windows')
        run: |
          make -v
          pwd
          ${{ matrix.make_cmd }}
        shell: msys2 {0}

      # - name: Generate Compressed File
      #   run: |
      #     cd ./bin
      #     zip juejin_collections-linux64.zip juejin_collections-linux64
      
      - name: Upload binaries to release
        uses: ncipollo/release-action@v1
        with:
          # 版本已存在是否允许更新
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "bin/${{ matrix.asset_name }}"
          tag: "v0.0.3-alpha"
          body: "test release v0.0.3-alpha"
